site:
  title: Shabad OS Tutorials
  url: https://tutorials.shabados.com
  start_page: tutorials::home.adoc

content:
  sources:
  - url: .

ui:
  bundle:
    url: ui/build/ui-bundle.zip
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"